# Generated by Django 5.2.5 on 2026-06-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], default='unidad', max_length=10, verbose_name='unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='stock mínimo')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='costo unitario')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'materia prima',
                'verbose_name_plural': 'materias primas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], default='unidad', max_length=10, verbose_name='unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='stock actual')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_terminados', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'producto terminado',
                'verbose_name_plural': 'productos terminados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('PRODUCCION', 'Producción')], max_length=15, verbose_name='tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='empresas.empresa', verbose_name='empresa')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.materiaprima', verbose_name='materia prima')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('producto_terminado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.productoterminado', verbose_name='producto terminado')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('ruc', models.CharField(blank=True, max_length=20, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_primas', to='inventario.proveedor', verbose_name='proveedor'),
        ),
    ]
