# Generated by Django 5.2.5 on 2026-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio'),
        ),
    ]
