# Generated by Django 5.2.5 on 2026-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productoterminado_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='código'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='ultima_vez_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='última vez actualizado'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='código'),
        ),
    ]
