# Generated by Django 5.2.5 on 2026-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_materiaprima_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tiempo_entrega_dias',
            field=models.PositiveIntegerField(default=3, help_text='Días que tarda el proveedor en entregar un pedido.', verbose_name='tiempo de entrega (días)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número con código de país sin + ni espacios. Ej: 51987654321', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_actual',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='stock actual'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='stock mínimo'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='stock_actual',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='stock actual'),
        ),
    ]
