# Generated by Django 5.2.5 on 2026-09-24 08:53

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_proveedor_tiempo_entrega_dias_proveedor_whatsapp_and_more'),
        ('produccion', '0003_alter_detalleformula_cantidad_requerida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=120)),
                ('anterior', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('nuevo', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='LeadTimeReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('cantidad_inicial', models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cantidad_disponible', models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrimaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_dias', models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(180)])),
                ('moq', models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('multiplo', models.DecimalField(decimal_places=5, default=1, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('presentacion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada', models.DateField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('APROBADA', 'APROBADA'), ('ENVIADA', 'ENVIADA'), ('CONFIRMADA', 'CONFIRMADA'), ('EN_TRANSITO', 'EN_TRANSITO'), ('RECIBIDA', 'RECIBIDA'), ('CERRADA', 'CERRADA')], default='APROBADA', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugerenciaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('calculo', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('explicacion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADA', 'APROBADA'), ('RECHAZADA', 'RECHAZADA'), ('OBSOLETA', 'OBSOLETA')], default='PENDIENTE', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='cobertura_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='gestionar_lotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='nivel_servicio',
            field=models.DecimalField(choices=[('0.900', '90 %'), ('0.950', '95 %'), ('0.975', '97.5 %'), ('0.990', '99 %')], decimal_places=3, default='0.950', max_digits=4),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddConstraint(
            model_name='productoterminado',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='productoterminado_stock_no_negativo'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumolote',
            name='consumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produccion.consumomateriaprima'),
        ),
        migrations.AddField(
            model_name='leadtimereal',
            name='detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='inventario.detalleordencompra'),
        ),
        migrations.AddField(
            model_name='lotemateriaprima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.materiaprima'),
        ),
        migrations.AddField(
            model_name='lotemateriaprima',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='consumolote',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lotemateriaprima'),
        ),
        migrations.AddField(
            model_name='materiaprimaproveedor',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='inventario.materiaprima'),
        ),
        migrations.AddField(
            model_name='materiaprimaproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.materiaprimaproveedor'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='proveedores',
            field=models.ManyToManyField(related_name='insumos', through='inventario.MateriaPrimaProveedor', to='inventario.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='materiaprima',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='materiaprima_stock_no_negativo'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.ordencompra'),
        ),
        migrations.AddField(
            model_name='reservainventario',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.materiaprima'),
        ),
        migrations.AddField(
            model_name='reservainventario',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sugerencias', to='inventario.materiaprima'),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.materiaprimaproveedor'),
        ),
    ]
