# Generated by Django 5.2.5 on 2026-09-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auditoria_consumolote_detalleordencompra_and_more'),
        ('produccion', '0004_consumomateriaprima_excluido_entrenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerenciacompra',
            name='pronostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.pronostico'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='sugerencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.sugerenciacompra'),
        ),
        migrations.AddConstraint(
            model_name='lotemateriaprima',
            constraint=models.UniqueConstraint(fields=('materia_prima', 'numero'), name='lote_unico'),
        ),
        migrations.AddConstraint(
            model_name='lotemateriaprima',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0), ('cantidad_disponible__lte', models.F('cantidad_inicial'))), name='lote_saldo_valido'),
        ),
        migrations.AddConstraint(
            model_name='materiaprimaproveedor',
            constraint=models.UniqueConstraint(fields=('materia_prima', 'proveedor'), name='oferta_unica'),
        ),
        migrations.AddConstraint(
            model_name='materiaprimaproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('moq__gte', 0), ('multiplo__gt', 0), ('precio__gte', 0)), name='oferta_valores_validos'),
        ),
        migrations.AddConstraint(
            model_name='detalleordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0), ('precio__gte', 0)), name='detalle_compra_valido'),
        ),
        migrations.AddConstraint(
            model_name='reservainventario',
            constraint=models.UniqueConstraint(fields=('orden', 'materia_prima'), name='reserva_orden_insumo'),
        ),
        migrations.AddConstraint(
            model_name='reservainventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='reserva_positiva'),
        ),
        migrations.AddConstraint(
            model_name='sugerenciacompra',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('materia_prima',), name='una_sugerencia_pendiente'),
        ),
    ]
