# Generated by Django 5.2.5 on 2026-09-24 09:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_proveedores_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='nivel_servicio',
            field=models.DecimalField(choices=[(Decimal('0.900'), '90 %'), (Decimal('0.950'), '95 %'), (Decimal('0.975'), '97.5 %'), (Decimal('0.990'), '99 %')], decimal_places=3, default='0.950', max_digits=4),
        ),
    ]
