# Generated by Django 5.2.5 on 2026-09-24 10:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_materiaprima_nivel_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_pedido',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha del pedido'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='materiaprimaproveedor',
            name='lead_time_dias',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='tiempo de entrega estimado (días)'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('APROBADA', 'Pendiente de llegada'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('EN_TRANSITO', 'En tránsito'), ('RECIBIDA', 'Recibida'), ('CERRADA', 'Cerrada')], default='APROBADA', max_length=15),
        ),
    ]
