# Generated by Django 5.2.5 on 2026-09-24 15:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_fechas_pedidos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerenciacompra',
            name='cantidad_editada',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Si se especifica, esta cantidad reemplaza la calculada al generar la orden.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))], verbose_name='cantidad editada por usuario'),
        ),
    ]
