# Generated by Django 5.2.5 on 2026-06-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20, verbose_name='rol'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='clave de sesión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='agente de usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='última actividad')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'sesión de usuario',
                'verbose_name_plural': 'sesiones de usuario',
                'ordering': ['-last_activity'],
            },
        ),
    ]
