# Generated by Django 5.2.5 on 2026-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_rol_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, verbose_name='empresa'),
        ),
    ]
