# Generated by Django 5.2.5 on 2026-06-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('cantidad_resultante', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad resultante')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='inventario.productoterminado', verbose_name='producto terminado')),
            ],
            options={
                'verbose_name': 'fórmula de producto',
                'verbose_name_plural': 'fórmulas de producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad requerida')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_formula', to='inventario.materiaprima', verbose_name='materia prima')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.formulaproducto', verbose_name='fórmula')),
            ],
            options={
                'verbose_name': 'detalle de fórmula',
                'verbose_name_plural': 'detalles de fórmula',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad producida')),
                ('observacion', models.TextField(blank=True, verbose_name='observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='produccion.formulaproducto', verbose_name='fórmula')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='inventario.productoterminado', verbose_name='producto terminado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'orden de producción',
                'verbose_name_plural': 'órdenes de producción',
                'ordering': ['-fecha'],
            },
        ),
    ]
