# Generated by Django 5.2.5 on 2026-07-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_materiaprima_codigo_and_more'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='cantidad producida')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='inventario.productoterminado', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'producción',
                'verbose_name_plural': 'producciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='cantidad usada')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.materiaprima', verbose_name='materia prima')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.produccion', verbose_name='producción')),
            ],
            options={
                'verbose_name': 'consumo de materia prima',
                'verbose_name_plural': 'consumos de materia prima',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='cantidad')),
                ('codigoMateriaPrima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_productos', to='inventario.materiaprima', verbose_name='materia prima')),
                ('codigoProductoTerminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='inventario.productoterminado', verbose_name='producto terminado')),
            ],
            options={
                'verbose_name': 'detalle de producto',
                'verbose_name_plural': 'detalles de producto',
                'unique_together': {('codigoMateriaPrima', 'codigoProductoTerminado')},
            },
        ),
    ]
