# Generated by Django 5.2.5 on 2026-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_produccion_consumomateriaprima_detalleproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleformula',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='cantidad requerida'),
        ),
        migrations.AlterField(
            model_name='formulaproducto',
            name='cantidad_resultante',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='cantidad resultante'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='cantidad producida'),
        ),
    ]
