# Generated by Django 5.2.5 on 2026-09-24 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auditoria_consumolote_detalleordencompra_and_more'),
        ('produccion', '0003_alter_detalleformula_cantidad_requerida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumomateriaprima',
            name='excluido_entrenamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumomateriaprima',
            name='motivo_exclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADA', 'PLANIFICADA'), ('RESERVADA', 'RESERVADA'), ('COMPLETADA', 'COMPLETADA'), ('CANCELADA', 'CANCELADA')], default='PLANIFICADA', max_length=15),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_planificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='receta_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='produccion',
            name='ejecutada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produccion',
            name='orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecucion', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='receta_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='produccion',
            name='sintetica',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('inicio', models.DateField(null=True)),
                ('fin', models.DateField(null=True)),
                ('registros', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=40)),
                ('metricas', models.JSONField(default=dict)),
                ('comparacion', models.JSONField(default=list)),
                ('parametros', models.JSONField(default=dict)),
                ('calidad', models.JSONField(default=dict)),
                ('validacion', models.JSONField(default=list)),
                ('artefacto', models.CharField(blank=True, max_length=200)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrenamientos', to='inventario.materiaprima')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('inicio', models.DateField()),
                ('horizonte', models.PositiveIntegerField()),
                ('valores', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=5, max_digits=20)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.entrenamiento')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pronosticos', to='inventario.materiaprima')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('real', models.FloatField()),
                ('predicho', models.FloatField()),
                ('error_absoluto', models.FloatField()),
                ('error_porcentual', models.FloatField(null=True)),
                ('pronostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='produccion.pronostico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pronostico', 'fecha'), name='evaluacion_fecha_unica')],
            },
        ),
    ]
