# Generated by Django 5.2.5 on 2026-09-24 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_materiaprima_nivel_servicio'),
        ('produccion', '0004_consumomateriaprima_excluido_entrenamiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producciones_ejecutadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumomateriaprima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.materiaprima', verbose_name='materia prima'),
        ),
        migrations.AlterField(
            model_name='consumomateriaprima',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='produccion.produccion', verbose_name='producción'),
        ),
        migrations.AlterField(
            model_name='detalleformula',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='produccion.formulaproducto', verbose_name='fórmula'),
        ),
        migrations.AlterField(
            model_name='detalleformula',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_formula', to='inventario.materiaprima', verbose_name='materia prima'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='codigoMateriaPrima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_productos', to='inventario.materiaprima', verbose_name='materia prima'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='codigoProductoTerminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_producto', to='inventario.productoterminado', verbose_name='producto terminado'),
        ),
        migrations.AlterField(
            model_name='formulaproducto',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='inventario.productoterminado', verbose_name='producto terminado'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.formulaproducto', verbose_name='fórmula'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='inventario.productoterminado', verbose_name='producto terminado'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='inventario.productoterminado', verbose_name='producto'),
        ),
    ]
