# Generated by Django 5.2.5 on 2026-09-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_produccion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='clave_operacion',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
