# Generated by Django 5.2.5 on 2026-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_produccion_clave_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='obsoleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produccion',
            name='anulada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
