# Generated by Django 5.2.5 on 2026-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_entrenamiento_obsoleto_produccion_anulada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='unidades_producidas',
            field=models.PositiveIntegerField(default=0, verbose_name='unidades producidas'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='cantidad producida (bulk kg)'),
        ),
    ]
